site_name: Introl's Knowledge Base
site_url: https://wiki.introl.top/
validation:
  links:
    absolute_links: relative_to_docs
    anchors: warn
    unrecognized_links: warn
theme:
  name: material
  features:
    - navigation.tabs
  palette:
    scheme: slate
    primary: black
  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
nav: 
  - 简介: README.md
  - OI: 
    - OI部分简介: OI/OI_README.md
    - 个人模板: 
      - README: OI/个人模板/个人模板_README.md
      - 总资料: OI/个人模板/总资料.md
    - 算法文章:
      - 简介: OI/算法文章/算法文章_README.md
      - 个人笔记:
        - 学习笔记-1-递归及递推: OI/算法文章/学习笔记-1-递归及递推.md
        - 学习笔记-2-DFS-BFS算法: OI/算法文章/学习笔记-2-DFS-BFS算法.md
        - 学习笔记-3-二分: OI/算法文章/学习笔记-3-二分
        - 学习笔记-4-前缀和-差分: OI/算法文章/学习笔记-4-前缀和-差分.md
      - 课件: OI/算法文章/课件.md
    - 题解集合: OI/题解集合/题解集合_README.md
    - 资源链接: OI/资源链接/资源链接_README.md
  - 文化课:
    - 文化课部分简介: 高中文化课/whk_README.md
    - 语文: 高中文化课/语文/语文_README.md
    - 数学: 高中文化课/数学/数学_README.md
    - 英语: 高中文化课/英语/英语_README.md
    - 物理: 高中文化课/物理/物理_README.md
    - 化学: 高中文化课/化学/化学_README.md
    - 生物: 高中文化课/生物/生物_README.md
    - 政治: 高中文化课/政治/政治_README.md
    - 地理: 高中文化课/地理/地理_README.md
    - 历史: 高中文化课/历史/历史_README.md

